Use -Wall in ros_controll
bit-bots/bitbots_lowlevel pull request #89
Opened 2021-05-30 15:50 UTC by jaagut

## Proposed changes
This adds the -Wall -Werror -Wno-unused flags to ros_controll.

## Related issues

## Necessary checks
- [x] Run `catkin build`
~- [ ] Write documentation~
~- [ ] Create issues for future work~
~- [ ] Test on your machine~
- [ ] Test on the robot
- [x] Put the PR on our Project board

2021-05-30 16:13 UTC, timonegk requested changes

2021-05-30 16:13 UTC, timonegk commented on bitbots_ros_control/src/pressure_converter.cpp
> +  while (zero_and_scale_values_[0].size() < size_t(scale_and_zero_average_)) {
What if `scale_and_zero_average_` is negative? The cast would make it a very large integer and the comparison would not make sense. Please cast the left hand side to whatever `scale_and_zero_average_` is (probably `int`).

2021-05-30 18:16 UTC, timonegk approved these changes

2021-05-30 19:25 UTC, jaagut commented
(Don't merge, until marc has approved this)

2021-05-31 06:51 UTC, SammyRamone approved these changes

2021-05-31 14:04 UTC, merged